spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feedly?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: tanhwan
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

server:
  port: 8080

news:
  api:
    key: b9a0d0952eff431e83bda1eb3deb2ef7
    url: https://newsapi.org/v2/everything